Export DC to mkversion.sh run in shell function
sociomantic-tsunami/makd pull request #24
Opened 2016-10-10 08:52 UTC by nemanja-boric-sociomantic

Shell function doesn't inherit variables exported
in Makefile, so explicit passing of `DC` is performed.

Fixes #23

2016-10-10 10:10 UTC, leandro-lucarella-sociomantic requested changes
`DC` is supposed to be exported, see https://github.com/sociomantic-tsunami/makd/blob/da527f1e33e00f1a0d02745d0fe366e602639c83/Makd.mak#L106-L108. My guess is `?=` is what is making it fail on some circumstances, I guess something like:

``` make
DC ?= ...
export DC
```

Should fix it.

2016-10-10 10:16 UTC, nemanja-boric-sociomantic commented
@leandro-lucarella-sociomantic I'm not sure that `DC` is exported to the subshell when called with `$(shell`

2016-10-10 10:18 UTC, nemanja-boric-sociomantic commented
https://bugs.debian.org/184864

2016-10-10 10:19 UTC, nemanja-boric-sociomantic commented
But, I'll try with `export DC`

2016-10-10 10:19 UTC, nemanja-boric-sociomantic commented
Yeah, it doesn't work.

2016-10-10 10:35 UTC, leandro-lucarella-sociomantic commented
:cry:

2016-10-10 10:35 UTC, leandro-lucarella-sociomantic commented
Add a comment with a link to the issue maybe?

2016-10-10 10:36 UTC, leandro-lucarella-sociomantic approved these changes

2016-10-10 10:39 UTC, nemanja-boric-sociomantic commented
Updated with the issue link in the commit message.

2016-10-10 13:12 UTC, mathias-lang-sociomantic commented
I'd also make the default in `mkversion.sh` refers to `dmd` instead of DMD1.
It shouldn't affect us, but will make the script more usable for upstream.

2016-10-10 15:14 UTC, leandro-lucarella-sociomantic requested changes
> I'd also make the default in mkversion.sh refers to dmd instead of DMD1.
> It shouldn't affect us, but will make the script more usable for upstream.

Yeah, I haven't saw the original issue before, it definitely make sense to change the default too (as a separate commit because they are 2 different things, but I think both are needed to fix the original issue properly).

2016-10-10 15:26 UTC, nemanja-boric-sociomantic commented
Updated.

2016-10-10 16:37 UTC, mathias-lang-sociomantic approved these changes
LGTM, thanks :)

2016-10-10 17:09 UTC, leandro-lucarella-sociomantic commented
> Updated with the issue link in the commit message.

Mmm, I meant a comment in the code (too), as I have the feeling someone (like me) would see explicit env var passing in the future and think is redundant and remove it :)

2016-10-11 10:08 UTC, nemanja-boric-sociomantic commented
You're such a pain :-).

Updated.

2016-10-11 13:29 UTC, leandro-lucarella-sociomantic approved these changes

2016-10-11 13:29 UTC, leandro-lucarella-sociomantic commented
> You're such a pain :-).

:kissing_heart:

2016-10-11 13:29 UTC, merged