Remove unused D_GC variable and documentation
sociomantic-tsunami/makd pull request #55
Opened 2017-03-01 14:58 UTC by mathias-lang-sociomantic

This doesn't seem to be used anywhere, hence why I targeted v1.x.x. Let me if you want to re-target.

OT: v1.x.x should probably be merged into v2.x.x (which is 50 commits behind).

2017-03-01 15:03 UTC, nemanja-boric-sociomantic commented
Why not rename it to `DRT_GCOPT`, as it is done in druntime?

2017-03-01 15:04 UTC, nemanja-boric-sociomantic commented
Ah, that was removed as well.

2017-03-01 16:20 UTC, leandro-lucarella-sociomantic commented
It is used (in D1), but in a very stealth way: https://github.com/sociomantic-tsunami/tangort/blob/v1.x.x/dmd1.conf#L4

That said, since the config file shipped in tangort now also provides a default (this was probably added before `dmd1.conf` supported adding a default value), I guess it's OK to remove the default. The problem is without the `export` like in Make, you can propagate the environment variable to the child process (`dmd1`) and thus you can't override it via `make`.

We can still use `D_GC=basic make` I think, and that would be propagated to `dmd1`, so we have a workaround (please test :) ), but this would qualify as a breaking change then, so I would favour going to v2.x.x branch (which I will get up to date soon).

2017-03-01 16:21 UTC, leandro-lucarella-sociomantic commented
> Why not rename it to DRT_GCOPT, as it is done in druntime?

They are not the same, `D_GC` is just a hack in the `dmd1.conf` shipped with tangort.

2017-03-01 16:27 UTC, mathias-lang-sociomantic commented
Didn't we remove the basic GC from tangort long ago though ?

2017-03-01 16:29 UTC, leandro-lucarella-sociomantic commented
> Didn't we remove the basic GC from tangort long ago though ?

Oh, [it looks like we did](https://github.com/sociomantic-tsunami/tangort/tree/v1.x.x/src/gc)! I do not recall at all that happened. Then we need to clean the `dmd1.conf` shipped by tangort too :grimacing:

2017-03-01 16:30 UTC, leandro-lucarella-sociomantic commented
Still, technically there are visible changes to the user, and since this change is not really buying us nothing, I would target v2.x.x anyway. Better be safe than sorry.

2017-03-01 16:30 UTC, leandro-lucarella-sociomantic commented
This also means adding a "Migration Instructions" note in the RELEASE NOTES.

2017-03-01 16:30 UTC, leandro-lucarella-sociomantic commented
#56

2017-03-01 16:33 UTC, leandro-lucarella-sociomantic requested changes
Needs release notes and blocked by #56.

2017-03-01 17:54 UTC, leandro-lucarella-sociomantic commented
Unblocked, #56 merged.

2017-03-01 17:56 UTC, mathias-lang-sociomantic commented
Updated

2017-03-02 14:31 UTC, leandro-lucarella-sociomantic requested changes

2017-03-02 14:31 UTC, leandro-lucarella-sociomantic commented on RELEASE_NOTES.md
> +* The `D_GC` variable available to `Build.mak` has been removed as there is only one GC available.
I would rephrase this with something more in the lines of a migration instruction, like:

> * The `D_GC` variable was removed as it wasn't used any more internally. if you made use of it anywhere, you should define it yourself (in `Config.mak` for example) from now on.

2017-03-08 13:04 UTC, mathias-lang-sociomantic commented
Updated

2017-03-08 16:55 UTC, leandro-lucarella-sociomantic approved these changes

2017-03-08 16:56 UTC, merged