pkg: Make OPTS and ARGS built-in
sociomantic-tsunami/makd pull request #68
Opened 2017-03-24 19:14 UTC by leandro-lucarella-sociomantic

Making OPTS and ARGS built-in variables allows built-in functions provided
by mkpkg to operate over them, thus allowing mkpkg to define more powerful
tools to users.

This also changes ``FUN.desc()`` not to take ``OPTS`` as an argument
anymore.

2017-03-24 19:15 UTC, leandro-lucarella-sociomantic commented
Depends on #67.

2017-03-25 21:45 UTC, gkotian requested changes

2017-03-25 21:45 UTC, gkotian commented on README.rst
> +built-in variables, some of which the user is expect to fill and some of which
`s/expect/expected`

2017-03-25 21:45 UTC, gkotian commented on README.rst
> +are tools for the user to define pacakges.
typo in `pacakges`.

2017-03-25 21:45 UTC, gkotian commented on README.rst
> +These variables should never be rebound (never assign to them like '`OPTS
s/'`OPTS/``OPTS

2017-03-25 21:45 UTC, gkotian commented on README.rst
>  passed to the ``mkpkg`` util. By default Makd pass the following variables:
`s/pass/passes`

2017-03-25 21:45 UTC, gkotian commented on RELEASE_NOTES.md
> +  Also, if you are using a ``defaults.py`` file, now just using ``ìmport
`s/now just using/now just use`

2017-03-25 21:45 UTC, gkotian commented on README.rst
> +``desc([type[, prolog[, epilog]]])``
This change should probably be made in the commit titled `Remove OPTS argument from FUN.desc()`.

2017-03-25 21:45 UTC, gkotian commented on README.rst
> +          description = FUN.desc('tools', epilog='These are just ' +
Ditto comment about moving this change to the commit titled `Remove OPTS argument from FUN.desc()`.

2017-03-28 15:57 UTC, leandro-lucarella-sociomantic commented
Updated.

2017-04-07 11:19 UTC, leandro-lucarella-sociomantic commented
Ping.

2017-04-07 11:21 UTC, nemanja-boric-sociomantic commented
Now with conflicts :-)

2017-04-07 11:40 UTC, leandro-lucarella-sociomantic commented
:boom:

2017-04-07 11:47 UTC, nemanja-boric-sociomantic approved these changes

2017-04-07 11:47 UTC, merged