Rename versionInfo to version_info
sociomantic-tsunami/makd pull request #72
Opened 2017-03-29 13:12 UTC by gkotian

Also deprecate versionInfo in the process.

Fixes #64.

2017-03-29 15:07 UTC, leandro-lucarella-sociomantic commented
I would do this for v1.x.x and completely remove `versionInfo` in v2.x.x instead.

2017-03-29 15:08 UTC, leandro-lucarella-sociomantic commented on RELEASE_NOTES.md
> +  remaining usage should be replaced with `version_info`.
Normally deprecations go into their own section. But I guess this will have to be changed when rebased to v1.x.x anyway.

2017-03-29 15:10 UTC, leandro-lucarella-sociomantic commented
I based the PR in v1.x.x, please rebase. After this we can merge to v2.x.x and remove the deprecated symbol.

2017-03-29 15:11 UTC, leandro-lucarella-sociomantic requested changes
Please rebase.

2017-03-29 19:09 UTC, gkotian commented
Rebased.

2017-03-29 20:00 UTC, llucax commented on Version.d.tpl
> +deprecated("'versionInfo' is deprecated. Please rename it to 'version_info'")
Why not using the `@MODULE@` in this message too?

2017-04-07 11:18 UTC, leandro-lucarella-sociomantic commented on Version.d.tpl
> +deprecated("'versionInfo' is deprecated. Please rename it to 'version_info'")
ping

2017-04-07 19:41 UTC, gkotian commented on Version.d.tpl
> +deprecated("'versionInfo' is deprecated. Please rename it to 'version_info'")
No reason. Will add it.

2017-04-07 19:42 UTC, gkotian commented
Updated with `@MODULE@` in the deprecation message.

2017-04-20 15:21 UTC, leandro-lucarella-sociomantic approved these changes

2017-04-20 15:21 UTC, merged