Move all unittest processing to the unittest target
sociomantic-tsunami/makd pull request #79
Opened 2017-04-26 12:39 UTC by leandro-lucarella-sociomantic

This commit moves the compilation and running of unittests to the
`unittest` target(s) and remove the flags `-unittest -debug=UnitTest
-version=UnitTest` when building integrationtests.

Fixes #41.

2017-04-26 12:40 UTC, leandro-lucarella-sociomantic commented
@mathias-baumann-sociomantic I would assign you but you didn't accept the invitation yet :)

2017-04-26 12:41 UTC, leandro-lucarella-sociomantic commented
BTW, untested, please do test!

2017-04-26 13:52 UTC, mihails-strasuns-sociomantic requested changes

2017-04-26 13:52 UTC, mihails-strasuns-sociomantic commented on Makd.mak
> +		$(call find_files,.d,,$C/test,$(TEST_FILTER_OUT))
This results in stuff like this in allunittests.d
```D
import .docker.ocean.test.unixlistener.main.d;
```
Maybe has something to do how `find_files` processes qualified paths?

2017-04-27 11:56 UTC, leandro-lucarella-sociomantic commented on Makd.mak
> +		$(call find_files,.d,,$C/test,$(TEST_FILTER_OUT))
Mmm, weird. It shouldn't.

2017-05-14 09:59 UTC, mihails-strasuns-sociomantic commented
Ping @leandro-lucarella-sociomantic

2017-05-17 12:36 UTC, leandro-lucarella-sociomantic commented
I found the problem, but we have  another issue, the extra `main()`s.

For now for the program we get around this by just not building/running unittests in the `main.d` file, but for tests is normal that they only have a `main.d` so skipping those will mean no running unittests at all. I think the only sensible thing to do here is to stop filtering-out `main.d` files and just force projects to use something like:

```d
version (UnitTest) {}
else
int main(...)
{
    // ...
}
```

Ideas/opinions?

2017-05-17 12:37 UTC, leandro-lucarella-sociomantic commented
@gavin-norman-sociomantic FYI, reading the last comment might be enough.

2017-05-17 13:11 UTC, leandro-lucarella-sociomantic commented
If we go this route, I need to update this PR to fix docs/release notes to note:

* The project's `main.d` files will no longer be auto-filtered-out from unittests (if we'll require that for `integrationtest` I think it doesn't make sense to exclude any files from `make unittest`, it's unnatural.

* All `main()` files need to be versioned-out when they are compiled with `version=UnitTest`.

* New `$(INTEGRATIONTEST)` variable.

2017-05-17 13:51 UTC, mihails-strasuns-sociomantic commented
I don't think we should do anything too smart here. This will come in a new makd major release - migration notes explaining the change and asking to adjust own code in appropriate manner would be enough.

2017-05-17 16:15 UTC, leandro-lucarella-sociomantic commented
> I don't think we should do anything too smart here. This will come in a new makd major release - migration notes explaining the change and asking to adjust own code in appropriate manner would be enough.

This means you agree with the proposed changes?

2017-05-19 13:34 UTC, leandro-lucarella-sociomantic commented
ping

2017-05-19 14:09 UTC, mihails-strasuns-sociomantic commented
What do you mean by `INTEGRATIONTEST` variable?

2017-05-19 15:04 UTC, leandro-lucarella-sociomantic commented on Makd.mak
> +INTEGRATIONTEST = test
This

2017-05-19 15:05 UTC, leandro-lucarella-sociomantic commented
Just a way to ease the path to using `integrationtest` instead in the future. Not really related to this but it was good to make it easier to find all the places where `test/` was used.

2017-05-19 15:11 UTC, mihails-strasuns-sociomantic commented
I see. Yeah, I do agree with propose path in that case.

2017-05-19 16:13 UTC, leandro-lucarella-sociomantic commented
OK, I will update with the docs before I forget what I've done :D

2017-05-19 16:20 UTC, leandro-lucarella-sociomantic commented
> What do you mean by INTEGRATIONTEST variable?

While at this, I think I will backport this to v1.x.x, so projects can already try changing `test/` to `integrationtest/` to see if that really fixes our problems with D2 and see if it fixes #74.

If this is the case, we can change the default in v2.x.x more confidently!

2017-05-19 16:41 UTC, leandro-lucarella-sociomantic commented
Updated! Please give this a close look before merging, it was a bit too long ago since last time I touched it :)

2017-05-22 15:57 UTC, leandro-lucarella-sociomantic commented
`INTEGRATIONTEST` backported via #82 which also addresses the related #74.

2017-05-22 16:01 UTC, leandro-lucarella-sociomantic commented
Added a commit to fix #74 (change the default location for integration tests).

2017-05-22 16:01 UTC, leandro-lucarella-sociomantic commented
ping @mihails-strasuns-sociomantic

2017-05-25 09:03 UTC, mihails-strasuns-sociomantic commented
Will re-test after #74 is merged

2017-05-30 15:54 UTC, leandro-lucarella-sociomantic commented
You mean #82, right?

2017-05-30 17:48 UTC, mihails-strasuns-sociomantic commented
Yep

2017-05-30 17:48 UTC, mihails-strasuns-sociomantic commented
Rebase?

2017-05-30 17:59 UTC, leandro-lucarella-sociomantic commented
Mmm, no? It seems to be at the current v2.x.x.

2017-05-30 18:00 UTC, leandro-lucarella-sociomantic commented
Ah, maybe you mean merge, because the other changes were done to v1.x.x, I think I will merge after the release of v1, but I guess I could merge now if you prefer.

2017-05-31 16:24 UTC, leandro-lucarella-sociomantic commented
OK, updated on top of the merge.

2017-05-31 16:26 UTC, leandro-lucarella-sociomantic commented
Created a new commit with just the merge: https://github.com/sociomantic-tsunami/makd/pull/83

2017-05-31 16:26 UTC, leandro-lucarella-sociomantic commented
So this PR can get less noisy after the merge is merged :D

2017-06-01 17:13 UTC, leandro-lucarella-sociomantic commented
OK, now it's clean again.

2017-06-01 18:26 UTC, mihails-strasuns-sociomantic approved these changes
Looks good!

2017-06-01 18:26 UTC, merged

2017-06-02 11:17 UTC, leandro-lucarella-sociomantic commented
:tada: