Add a warning when using "test" for integration tests
sociomantic-tsunami/makd pull request #82
Opened 2017-05-22 15:55 UTC by leandro-lucarella-sociomantic

Also introduce the variable INTEGRATIONTEST.

To improve compatibility with D2, the default location of the integration tests will change from `test` to `integrationtest`, so we need to warn the user about this.

The warning can be disabled by explicitly defining the `INTEGRATIONTEST` variable.

This is the v1.x.x part of #74.

2017-05-25 09:01 UTC, mihails-strasuns-sociomantic requested changes

2017-05-25 09:01 UTC, mihails-strasuns-sociomantic commented on Makd.mak
> +ifndef INTEGRATIONTEST
I tried defining `INTEGRATIONTEST:=test` in `Config.mak` but message keeps being printed

2017-05-30 09:01 UTC, leandro-lucarella-sociomantic commented on Makd.mak
> +ifndef INTEGRATIONTEST
Right! Currently it is a bit messy what can be overridden by `Config.mak`, I should probably clean that up at some point.

2017-05-30 09:02 UTC, leandro-lucarella-sociomantic commented
Updated.

2017-05-30 13:50 UTC, mihails-strasuns-sociomantic commented
Still doesn't work for me with `Config.mak`

2017-05-30 15:49 UTC, leandro-lucarella-sociomantic commented
That's weird, it works for me:
```
$ git fetch https://github.com/leandro-lucarella-sociomantic/makd.git deprecate-74
From https://github.com/leandro-lucarella-sociomantic/makd
 * branch            deprecate-74 -> FETCH_HEAD

$ git checkout -b test FETCH_HEAD

$ make SRC=. -f Makd.mak 
MakD Warning: The default location of integration tests (defined by $(INTEGRATIONTEST) and 'test' by default now) will change to 'integrationtest' in v2.0.0. If you want to avoid this warning, please define it explicitly in your Config.mak.
make: Nothing to be done for 'all'.

$ echo 'INTEGRATIONTEST := lala' > Config.mak

$ make SRC=. -f Makd.mak 
make: Nothing to be done for 'all'.
```

2017-05-30 15:50 UTC, leandro-lucarella-sociomantic commented
Ah, I think I pushed the latest changes after you tested, there was a pending issue :D

2017-05-30 16:04 UTC, mihails-strasuns-sociomantic commented
Yep, works now!

2017-05-30 16:04 UTC, mihails-strasuns-sociomantic approved these changes

2017-05-30 16:04 UTC, merged